### ISSUE TITLE
Issue with Type Ambiguity

### ISSUE THREAD

**Issue by PeterPanino** [WladiD/SendInputHelper#1]
If there is a **System.Classes** in the _Uses_ clause, a TYPE AMBIGUITY error may arise. This forces the user to prefix the _TSIHShiftState_ parameter with the _SendInputHelper_ name-space:

`SIH.AddShortCut([SendInputHelper.ssCtrl], 'V'); // CTRL+V`

And it also forces the user to prefix the _TShiftState_ parameter with the _System.Classes_ name-space, e.g. in a _OnKeyUp_ event-handler:

```
procedure TForm1.MyControlKeyUp(Sender: TObject; var Key: Word; Shift: TShiftState);
begin
  if (Shift = [System.Classes.ssCtrl]) and (Key = VK_V) then
  begin
    DoSomething;
  end;
end;
```

**Comment by WladiD** [comment]
Hi Peter,

i know about this limitation, in such cases my simple solution is to move `SendInputHelper` in the uses section before `System.Classes`. But then you are forced to prefix them for TSendInputHelper calls.

Do you have a better solution?
